---
- name: "Create directories"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  loop:
    - "{{ uv_bin_dir }}"
    - "{{ uv_src_dir }}"

- name: "Get GitHub release information"
  run_once: true
  delegate_to: localhost
  delegate_facts: true
  when:
    - "'github_uv_release_info' not in hostvars['localhost'].ansible_facts"
  block:
    - name: "Get GitHub release information"
      ansible.builtin.uri:
        url: >-
          {{ "https://api.github.com/repos/" + uv_github_org + "/" + uv_github_repo
             + "/releases"
             + ("/tags" if uv_version != "latest" else "") + "/" + uv_version }}
        method: GET
        return_content: true
        status_code: 200
        body_format: json
        headers: >-
          {{ {"Authorization": "Bearer " + uv_github_token}
             if uv_github_token != "" else {} }}
      retries: 6
      delay: 15
      register: _release_info
      check_mode: false

    - name: Cache GitHub release information
      ansible.builtin.set_fact:
        github_uv_release_info: "{{ _release_info.json }}"
        cacheable: true

- name: Download release archive
  vars:
    _uv_archive_url: >-
      {{ hostvars["localhost"].ansible_facts.github_uv_release_info.assets
         | selectattr("name", "search", "uv", ignorecase=true)
         | selectattr("name", "search", "linux", ignorecase=true)
         | selectattr("name", "search", ansible_facts.architecture, ignorecase=true)
         | selectattr("name", "search", "\."+uv_archive_extension+"$")
         | map(attribute='browser_download_url')
         | first
         | default(None) }}
    _uv_archive_filename: "{{ _uv_archive_url | split('/') | last }}"
    _uv_checksum_url: >-
      {{ hostvars["localhost"].ansible_facts.github_uv_release_info.assets
         | selectattr("name", "equalto", _uv_archive_filename+"."+uv_checksum_type)
         | map(attribute='browser_download_url')
         | first
         | default(None) }}
    _uv_archive_checksum: >-
      {{ lookup('url', _uv_checksum_url, wantlist=True)
         | select('search', "\s"+_uv_archive_filename+"$")
         | first | default('') | split(' ') | first | default(None) }}
  block:
    - name: "Download archive"
      ansible.builtin.get_url:
        url: "{{ _uv_archive_url }}"
        dest: "{{ uv_src_dir }}/{{ _uv_archive_filename }}"
        checksum: "{{ uv_checksum_type }}:{{ _uv_archive_checksum }}"
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      retries: 6
      delay: 15

    - name: "Extract files from archive"
      ansible.builtin.unarchive:
        src: "{{ uv_src_dir }}/{{ _uv_archive_filename }}"
        remote_src: true
        dest: "{{ uv_bin_dir }}"
        extra_opts:
          - "--strip-components={{ uv_strip_components }}"
          - "--wildcards"
          - "--no-anchored"
          - "{{ item }}"
        owner: root
        group: root
      loop: "{{ uv_src_files }}"
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Get downloaded archive files
      ansible.builtin.find:
        paths: "{{ uv_src_dir }}"
        patterns: "{{ '*' + _uv_archive_filename | splitext | last }}"
      register: _uv_src_archives

    - name: Remove older downloaded archive files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ _uv_src_archives.files }}"
      loop_control:
        label: "{{ item.path }}"
      when:
        - "item.path | basename != _uv_archive_filename"
        - "uv_clean_src_dir | bool"

- name: "Create symbolic links for CLI tool binaries in /usr/local/bin"
  ansible.builtin.file:
    src: "{{ uv_bin_dir }}/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: root
    state: link
  loop: "{{ uv_cli_tools }}"

- name: "Enable uv update systemd timer"
  when: uv_update_time != "never"
  block:
    - name: Add uv update service
      ansible.builtin.template:
        src: uv-update.service
        dest: "/etc/systemd/system/uv-update.service"
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      register: _service_file

    - name: Add uv update systemd timer
      ansible.builtin.template:
        src: uv-update.timer
        dest: "/etc/systemd/system/uv-update.timer"
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      register: _timer_file

    - name: Start and enable uv update systemd timer
      ansible.builtin.systemd:
        name: uv-update.timer
        daemon_reload: >-
          {{ true if _service_file is changed or _timer_file is changed else false }}
        state: started
        enabled: true

- name: "Disable uv update systemd timer"
  when: uv_update_time == "never"
  block:
    - name: Remove uv update service and timer
      ansible.builtin.file:
        path: "/etc/systemd/system/{{ item }}"
        state: "absent"
      loop:
        - "uv-update.service"
        - "uv-update.timer"
      register: _remove_files

    - name: Disable uv update systemd timer
      ansible.builtin.command:
        cmd: systemctl disable uv-update.timer
      register: _systemctl_disable
      changed_when: "'removed' in _systemctl_disable.stderr | lower"
      when: _remove_files is changed
